"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { api } from "@/lib/api";
import type { SimilarIdea } from "@/lib/types";

interface SimilarIdeasPanelProps {
  ideaId: string;
}

/**
 * SimilarIdeasPanel - Displays ideas similar to the current one.
 *
 * Uses the SimilarityService (via api.ideas.similar) which performs
 * vector similarity search on embeddings generated by sync handlers.
 */
export function SimilarIdeasPanel({ ideaId }: SimilarIdeasPanelProps) {
  const [similarIdeas, setSimilarIdeas] = useState<SimilarIdea[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isCollapsed, setIsCollapsed] = useState(false);

  useEffect(() => {
    async function loadSimilar() {
      try {
        setIsLoading(true);
        const data = await api.ideas.similar(ideaId);
        setSimilarIdeas(data);
      } catch (error) {
        console.error("Failed to load similar ideas:", error);
      } finally {
        setIsLoading(false);
      }
    }

    loadSimilar();
  }, [ideaId]);

  if (isLoading) {
    return (
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium">Similar Ideas</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-xs text-muted-foreground">Loading...</p>
        </CardContent>
      </Card>
    );
  }

  if (similarIdeas.length === 0) {
    return null;
  }

  return (
    <Card>
      <CardHeader
        className="cursor-pointer pb-2"
        onClick={() => setIsCollapsed(!isCollapsed)}
      >
        <div className="flex items-center justify-between">
          <CardTitle className="text-sm font-medium">
            Similar Ideas ({similarIdeas.length})
          </CardTitle>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className={`transition-transform ${isCollapsed ? "" : "rotate-180"}`}
          >
            <path d="m18 15-6-6-6 6" />
          </svg>
        </div>
      </CardHeader>
      {!isCollapsed && (
        <CardContent>
          <ScrollArea className="max-h-[200px]">
            <div className="space-y-2">
              {similarIdeas.map((idea) => (
                <Link
                  key={idea.idea_id}
                  href={`/ideas/${idea.idea_id}`}
                  className="block rounded-md border p-2 transition-colors hover:bg-accent"
                >
                  <p className="text-sm font-medium">{idea.title}</p>
                  <span className="text-xs text-muted-foreground">
                    {Math.round(idea.similarity * 100)}% similar
                  </span>
                </Link>
              ))}
            </div>
          </ScrollArea>
        </CardContent>
      )}
    </Card>
  );
}
